### PR TITLE
chore: setup unit testing tools

### LINKED ISSUE #1: Unit tests
## Description

Currently, the application does not have any tests. Thus, we should write unit tests.

## Motivation

Testing your Angular application helps you check that your app is working as you expect.

## Suggested Implementation

- Migrate from Karma to Jest
- Start adding unit tests

## Alternate Implementations

N/A

### PR DESCRIPTION
**Pull request by theoklitosBam7**
- Add and configure Jest for unit testing.
- Remove Karma and Jasmine related packages.
- Add @angular-builders/jest that allows us running `ng test` with Jest instead of Karma & Jasmine.
- Add @ngneat/spectator to simplify unit tests.

Partially resolves #1

### CODE REVIEW

**Comment by nikosanif** [comment]
Hey @theoklitosBam7! Many thanks for your contribution. It's a big step towards writing tests! 👏 

However, I have a generic question before the code review. As I am new to writing tests, I noticed a new file `jest-global-mocks.ts`. Can you explain in short what this file is? Alternatively, you can provide resources (e.g documentation links, articles) where I can find more information about this file.

**Comment by theoklitosBam7** [comment]
Hi @nikosanif !

Because `jest-preset-angular` uses `JSDOM`, which is different from normal browsers, we might need some global browser mocks to stimulate the behaviors of real browsers in `JSDOM`. To add global mocks, we can create `jest-global-mocks.ts` (name doesn’t matter) and use it in our Jest setup. For example, I had to mock `IntersectionObserver` because of Taiga UI problems during unit tests run. As Karna uses a real browser we didn’t need that.

You may find more information about `jest-preset-angular` in official [docs](https://thymikee.github.io/jest-preset-angular/) and about Jest and JSDOM in this [article](https://freecontent.manning.com/testing-with-node-jest-and-jsdom/).

**Comment by nikosanif** [comment]
Thanks, @theoklitosBam7 for your answer! 💯

**Review by nikosanif — APPROVED** [review]
LGTM

**Pull request merged**
